apiVersion: apps/v1
kind: Deployment
metadata:
  name: mipengine-localnode-deployment
  labels:
    app: mipengine-localnode
spec:
  replicas: {{ .Values.localnodes }}
  selector:
    matchLabels:
      app: mipengine-localnode
  template:
    metadata:
      labels:
        app: mipengine-localnode
    spec:
      nodeSelector:
        nodeType: worker
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mipengine-localnode
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: monetdb
        image: {{ .Values.mipengine_images.repository }}/mipenginedb:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 50000
        volumeMounts:
        - mountPath: /home/monetdb
          name: monetdb-data

      - name: rabbitmq
        image: {{ .Values.mipengine_images.repository }}/mipengine_rabbitmq:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_ADMIN_USER
          value: "user"
        - name: RABBITMQ_ADMIN_PASSWORD
          value: "password"
        - name: RABBITMQ_ADMIN_VHOST
          value: "user_vhost"
        - name: RABBITMQ_SLEEP_BEFORE_CONFIGURATION
          value: "30"
        ports:
          - containerPort: 5672

      - name: node
        image: {{ .Values.mipengine_images.repository }}/mipengine_node:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_IDENTIFIER
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_ROLE
          value: "LOCALNODE"
        - name: LOG_LEVEL
          value: "INFO"
        - name: RABBITMQ_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RABBITMQ_PORT
          value: "5672"
        - name: MONETDB_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MONETDB_PORT
          value: "50000"

      volumes:
      - name: monetdb-data
        hostPath:
          path: {{ .Values.monetdb_storage }}

---

apiVersion: v1
kind: Service
metadata:
  name: mipengine-localnode-service
spec:
  clusterIP: None
  selector:
    app: mipengine-localnode
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
