apiVersion: apps/v1
kind: Deployment
metadata:
  name: mipengine-globalnode-deployment
  labels:
    app: mipengine-globalnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mipengine-globalnode
  template:
    metadata:
      labels:
        app: mipengine-globalnode
    spec:
      nodeSelector:
        nodeType: master
      containers:
      - name: mipengine-monetdb
        image: {{ .Values.mipengine_images.repository }}/mipenginedb:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 50000

      - name: mipengine-rabbitmq
        image: {{ .Values.mipengine_images.repository }}/mipengine_rabbitmq:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_ADMIN_USER
          value: "user"
        - name: RABBITMQ_ADMIN_PASSWORD
          value: "password"
        - name: RABBITMQ_ADMIN_VHOST
          value: "user_vhost"
        - name: RABBITMQ_SLEEP_BEFORE_CONFIGURATION
          value: "30"
        ports:
          - containerPort: 5672

      - name: mipengine-node
        image: {{ .Values.mipengine_images.repository }}/mipengine_node:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_IDENTIFIER
          value: "globalnode"
        - name: NODE_ROLE
          value: "GLOBALNODE"
        - name: LOG_LEVEL
          value: "INFO"
        - name: NODE_REGISTRY_IP
          value: "mipengine-noderegistry-service"
        - name: NODE_REGISTRY_PORT
          value: "8500"
        - name: RABBITMQ_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RABBITMQ_PORT
          value: "5672"
        - name: MONETDB_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MONETDB_PORT
          value: "50000"

