apiVersion: apps/v1
kind: Deployment
metadata:
  name: mipengine-localnode-deployment
  labels:
    app: mipengine-node
    nodeType: localnode
spec:
  replicas: {{ .Values.localnodes }}
  selector:
    matchLabels:
      app: mipengine-node
  template:
    metadata:
      labels:
        app: mipengine-node
        nodeType: localnode
    spec:
      nodeSelector:
        nodeType: worker
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mipengine-node
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: monetdb
        image: {{ .Values.mipengine_images.repository }}/mipenginedb:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_LEVEL
          value: {{ .Values.log_level }}
        ports:
          - containerPort: 50000
        volumeMounts:
        - mountPath: /home/monetdb
          name: db-data

      - name: db-importer
        image: {{ .Values.mipengine_images.repository }}/mipengine_mipdb:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DB_PORT
          value: "50000"
        volumeMounts:
        - mountPath: /opt/data
          name: csv-data

      - name: rabbitmq
        image: {{ .Values.mipengine_images.repository }}/mipengine_rabbitmq:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_ADMIN_USER
          value: "user"
        - name: RABBITMQ_ADMIN_PASSWORD
          value: "password"
        - name: RABBITMQ_ADMIN_VHOST
          value: "user_vhost"
        - name: RABBITMQ_SLEEP_BEFORE_CONFIGURATION
          value: "30"
        ports:
          - containerPort: 5672

      - name: node
        image: {{ .Values.mipengine_images.repository }}/mipengine_node:{{ .Values.mipengine_images.version }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_IDENTIFIER
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_ROLE
          value: "LOCALNODE"
        - name: LOG_LEVEL
          value: {{ .Values.log_level }}
        - name: FRAMEWORK_LOG_LEVEL
          value: {{ .Values.framework_log_level }}
        - name: RABBITMQ_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RABBITMQ_PORT
          value: "5672"
        - name: MONETDB_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MONETDB_PORT
          value: "50000"
        - name: SMPC_ENABLED
          value: {{ quote .Values.smpc.enabled }}
        - name: SMPC_OPTIONAL
          value: {{ quote .Values.smpc.optional }}

      volumes:
      - name: db-data
        hostPath:
          path: {{ .Values.monetdb_storage }}
      - name: csv-data
        hostPath:
          path: {{ .Values.csvs_datapath }}
