localnodes: 2

mipengine_images:
  repository: madgik
  version: latest

log_level: INFO
framework_log_level: INFO

cdes_path: /opt/data
monetdb_storage: /opt/monetdb

controller:
  node_landscape_aggregator_update_interval: 30
  celery_tasks_timeout: 60

smpc:
  enabled: false
  optional: false
