mipengine_images:
  repository: madgik
  version: latest

log_level: DEBUG
framework_log_level: DEBUG

cdes_path: /opt/data

monetdb_storage: /opt/monetdb

controller:
  node_registry_update_interval: 30
  celery_tasks_timeout: 60

localnodes: 2
