log_level = "INFO"
cdes_metadata_path = "$CDES_METADATA_PATH"

deployment_type="$DEPLOYMENT_TYPE"

node_registry_update_interval=10
node_registry_get_node_info_timeout=10

[localnodes]
config_file="$LOCALNODES_CONFIG_FILE"
dns="$LOCALNODES_DNS"
port="$LOCALNODES_PORT"

[rabbitmq]
user = "user"
password = "password"
vhost = "user_vhost"
